# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce27e7a092e9746c194a88e31c493672ef841cd8921edc0021bc30e251e54164efc8a3d813effd4ea67594d9398dd8d667bb155d772889fc16a6d940e0dca351

test:
  secret_key_base: 0f8097323069a8fe032258b6dd08811fc2af1e7b65d60ca836ec3661d987769b2e9f2f288264d1d35f05c1d494d52bf7d9ad1e30685dfb5fd11a0545973151f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
